services:

  worker-html:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw4_worker_html
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/worker_html.py
    restart: "no"

  worker-js:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw4_worker_js
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/worker_js.py
    depends_on:
      worker-html:
        condition: service_completed_successfully
    restart: "no"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw4_scheduler
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/scheduler.py
    depends_on:
      worker-js:
        condition: service_completed_successfully
    restart: "unless-stopped"